server:
    port: 8004
mybatis:
    mapper-locations: classpath:mapper/*.xml
spring:
    profiles:
        active: ${spring.active}
    mvc:
        static-path-pattern: /static/**
    resources:
        static-locations: classpath:/static/
    data:
        mongodb:
            database: video_db
            host: 192.168.249.48
            port: 27017
            username: tt@king
            password: xinrui.123
            authentication-database: admin
